# Generated by Django 3.2.3 on 2021-05-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mot_de_passe', '0002_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mot_de_passe',
            new_name='Mots',
        ),
    ]
