# Generated by Django 3.2.3 on 2021-06-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mot_de_passe', '0003_rename_mot_de_passe_mots'),
    ]

    operations = [
        migrations.AddField(
            model_name='mots',
            name='difficulte',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mots',
            name='theme',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mots',
            name='utilisateur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
