# Generated by Django 3.2.3 on 2021-06-30 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mot_de_passe', '0004_auto_20210630_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
