# Generated by Django 3.2.3 on 2021-07-01 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mot_de_passe', '0006_alter_score_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
